name: Nightly Rust

on:
  push:
    branches: [ "dev" ]

  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:
    inputs:
      nightly:
        description: "Create nightly release"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            artifact-name: unknownlang-linux
            binary-name: unknownlang

          - os: windows-latest
            target: windows
            artifact-name: unknownlang-windows
            binary-name: unknownlang.exe

          - os: macos-latest
            target: macos
            artifact-name: unknownlang-macos
            binary-name: unknownlang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --verbose

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p dist
          cp target/release/${{ matrix.binary-name }} dist/${{ matrix.artifact-name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/${{ matrix.artifact-name }}

  create-nightly-release:
    name: Nightly Release
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: ${{ (github.event_name == 'push' || inputs.nightly) && !cancelled() }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: nightly
          name: Development Build

          body: |
            This is a nightly build of **Unknown Language** for commit ${{ github.sha }} from ${{ github.ref_name }} branch.

            This is a development release of **Unknown Language**.
            It is not recommended for production use.
            Please use this version only for testing and development

          files: |
            artifacts/unknownlang-linux/unknownlang-linux
            artifacts/unknownlang-windows/unknownlang-windows
            artifacts/unknownlang-macos/unknownlang-macos